### PR TITLE
Wait for custom future instead of reaction check when drafting teams

### LINKED ISSUE #14: [develop] Team drafting stalls after all users are picked
When the team drafting finishes (all users have been picked) the picks remain there and the bot doesn't move to where it sends the API call to the server to start the match. It doesn't even get to the embed that says `Fetching server...`.

The issue here is with the how the handlers for the reaction_add event work [here](https://github.com/csgo-league/csgo-league-bot/blob/1f60433d9affde38ab404d12ca5c123c8441707d/bot/cogs/teamdraft.py#L159). Two handlers are registered and the order they complete in when a reaction is added is arbitrary. When the reaction for the last pick is made, the issue occurs when the `wait_for()` handler (that checks if there are no users left to draft) processes before the `_process_pick()` handler does:
1. Reaction for last pick is made.
2. `wait_for()` handler processes first, and returns `False` because the user being last pick hasn't removed from `users_left` yet.
3. `_process_pick()` is processed second and removes the user pick from `users_left`.
4. The `wait_for()` handler keeps waiting, because no more reactions have been made despite there `users_left` being empty.

The current workaround is to react again after the team draft finishes and it won't stall any longer.

### PR DESCRIPTION
**Pull request by cameronshinn**
Closes #14

### CODE REVIEW

**Comment by cameronshinn** [comment]
This solution makes it so there aren't two independent handlers listening to the "on_reaction" event. This way we can have full control over the order everything executes in, because it's all done in the `_process_pick()` function. Using a futures attribute allows us to control the waiting time from within the only "on_reaction" handler.

**Review by B3none — APPROVED** [review]
Code-wise it seems good to me, it's a little Python-specific for me but so long as it's tested and working I see no reason why this shouldn't be merged.

**Comment by cameronshinn** [comment]
So basically instead of having one handler to process the picks, and another handler to tell if it's all done, I got rid of the done handler and just make it wait until the other handler tells it it's done (what the future object is for). This prevents the done handler from running before the handler to process the pick runs, so it will always check if there are no users left to pick from after the last pick is processed, rather than before. Hope that makes some sense.

**Comment by cameronshinn** [comment]
Oops I closed before merging

**Pull request merged**
