### PR TITLE
Autobalance improve by @thboss

### PR DESCRIPTION
**Pull request by 39ma**

### CODE REVIEW

**Comment by cameronshinn** [comment]
@39ma or @thboss can you explain what this change is doing? To me it looks like reorders the code and removes the sorting of players by their RankMe score, which is crucial to how the auto-balancing works. I must be missing something...

**Comment by B3none** [comment]
I was just thinking about whether there's a way we could implement machine learning to generate the teams based off of a players match performance and aim for a 15-15 game. We could then feed the data in and progressively train the model.

**Comment by thboss** [comment]
@cameronshinn get_players() doesn't sort callback correctly so we need to sort it based on users ids list,

**Comment by thboss** [comment]
And yes, @39ma you made mistake by remove lines 504-505

**Comment by cameronshinn** [comment]
@thboss Ah yes I remember operating under the assumption that order was preserved when getting the API response.

Could you push this fix down the stack into the [`ApiHelper.get_players()`](https://github.com/csgo-league/csgo-league-bot/blob/febbd26f48fc32dfeba4bc91f501e440d85d594e/bot/helpers/api.py#L273) method instead? Preserving the order of the response doesn't seem like something the bot should be worrying about.

**Comment by thboss** [comment]
@cameronshinn I can't edit files due to permissions
anyway, it just need to add this line into get_players()
```py
players.sort(key=lambda x: user_ids.index(int(x['discord'])))
```

**Comment by cameronshinn** [comment]
@thboss I can add it

**Comment by cameronshinn** [comment]
Fixed by 0fa0204

**Pull request closed without merging**
