### PR TITLE
check valid name

### LINKED ISSUE #25: Unicode characters in team player names are displaying as escaped hex values in-game
#24 is attempting to solve the issue with unicode characters in Discord usernames by preventing players with names including unicode characters from joining the queue. Turns out that the aiohttp [`ClientSession`](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=session#aiohttp.ClientSession) is converting the request JSON payload data to ASCII in the [`start_match()`](https://github.com/csgo-league/csgo-league-bot/blob/ffe3a1ab7908eb40e05afa831bf6e6d696a16db3/bot/helpers/api.py#L235) API helper function. A better fix would be to change the JSON encoder of the `ClientSession` to convert JSON data to unicode instead of ASCII.

### PR DESCRIPTION
**Pull request by thboss**

### CODE REVIEW

**Comment by cameronshinn** [comment]
Can you explain the purpose of these changes?

**Comment by thboss** [comment]
for example
if the player's name has characters like `Ð å ń G è R` will stores in the database like `\u00d0 \u00e5 \u0144 G \u00e8 R`
these changes to check if the player's name has a character non-ASCII then can't join the queue
and he should change his nickname in the server (to valid name) to do that

**Comment by cameronshinn** [comment]
Instead of preventing them from joining the queue could we modify their name when it's entered into the database (when creating a match)? We can replace non-ascii characters with something ascii. There might be other reasons server members want to have those characters in their name so IMO it would be better to let them join and have their name display differently in-game. I know unicode is allowed for in-game names anyways. Is it possible for us to have the discord name column be unicode in the web panel DB @b3none?

**Comment by thboss** [comment]
@cameronshinn I think that's can be done in `get5_apistats` plugin by converting Decode to Unicode [here](https://github.com/splewis/get5/blob/8890db87689cb17d841fc8baae7e3cf061c30c2f/scripting/get5_apistats.sp#L302)

**Comment by cameronshinn** [comment]
Oh so does get5 only allow ascii for player names? For now you could just convert the non-ascii names to ascii?

**Comment by thboss** [comment]
`Oh so does get5 only allow ascii for player names?` I think yes.
not convert to ASCII, I meant to convert `name` to Unicode when fetching name from database

`\u00d0 \u00e5 \u0144 G \u00e8 R`   to  `Ð å ń G è R`

**Comment by cameronshinn** [comment]
So is the issue with the database not storing names in unicode or get5 not being able to display unicode names?

**Comment by thboss** [comment]
I think it's get5 issue because I have plugins can store unicode in database

**Comment by cameronshinn** [comment]
So then we have two options the way I see it.

1. Convert discord usernames to all ASCII when passing them as names for [`start_match`](https://github.com/csgo-league/csgo-league-bot/blob/ffe3a1ab7908eb40e05afa831bf6e6d696a16db3/bot/cogs/match.py#L235).
2. Modify get5 to accept unicode usernames.

@b3none any opinion on this?

**Comment by torriz** [comment]
> So then we have two options the way I see it.
> 
> 1. Convert discord usernames to all ASCII when passing them as names for [`start_match`](https://github.com/csgo-league/csgo-league-bot/blob/ffe3a1ab7908eb40e05afa831bf6e6d696a16db3/bot/cogs/match.py#L235).
> 2. Modify get5 to accept unicode usernames.
> 
> @b3none any opinion on this?

If anyone knows how and what to look for: 2. Modify get5 😃 

EDIT: I know you didn't ask me but 👼

**Comment by cameronshinn** [comment]
Naw all input is appreciated. @thboss said it's probably [here](https://github.com/splewis/get5/blob/8890db87689cb17d841fc8baae7e3cf061c30c2f/scripting/get5_apistats.sp#L302).

**Comment by torriz** [comment]
Sorry if this was already explained but..

I'm failing to understand how:

> name getting stored in db => \u00d0 \u00e5 \u0144 G \u00e8 R

**How and what is storing it in the db?** 
Isn't it the /web/ api part FROM a post request from bot that stores the discord name, for use in cs?
or is it the name FROM cs that is stored by get5 => to db?

**Comment by torriz** [comment]
and/or is non-ascii/unicode supposed to be stored like that in mysql?

**Comment by cameronshinn** [comment]
I'm not sure that there is anything wrong with the MySQL implementation. That representation of unicode is how they can be represented in Python. It could be that the request JSON is getting converted to ASCII by the aiohttp Python library in the when the request is sent to the API?

**Comment by cameronshinn** [comment]
Maybe the codec when the JSON is created is in ASCII.

**Comment by cameronshinn** [comment]
Yes I found the reason [here](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=session#aiohttp.ClientSession) is caused by the JSON codec argument. It uses the default `json.dumps()` call which converts unicode to ASCII representations unless you specify `'utf-8'` as the codec argument.

**Comment by cameronshinn** [comment]
@thboss I created an issue for this. Can you tackle that one for me? You can assign yourself.

**Pull request closed without merging**
