### PR TITLE
Change embed for picking.

### PR DESCRIPTION
**Pull request by ScottUK**
Hopefully makes it look a bit nicer. :)

### CODE REVIEW

**Comment by B3none** [comment]
Have you got a screenshot so we can see what it looks like?

**Comment by ScottUK** [comment]
image

Could only test with myself and a test account, would look a lot better with more players as well.

**Comment by cameronshinn** [comment]
I will try make the forced pick order changes tonight and then you can implement it into your embed. You'll have to merge `develop` into your branch. After that we can merge yours assuming everything looks good.

**Comment by ScottUK** [comment]
👍 Sounds good.

**Comment by cameronshinn** [comment]
I implemented a forced pick order on the `team-draft-enhancements` branch. It's not tested yet. If you test it and it looks good you can merge that branch into your PR branch and then use the `_active_picker` attribute. Then before we complete your PR I will merge that branch into `develop` and it will look like my team draft changes were there in the first place.

**Comment by cameronshinn** [comment]
Added the stuff in the "Game Info" section to the picking embed already.

**Pull request closed without merging**
