### PR TITLE
Modern python notation / formatting & improved performance

### PR DESCRIPTION
**Pull request by WardPearce**
Thought I might look over the CSGO League bot again recently. The following PR will most likely break other parts of the bot, but most of the changes I made here I think should be applied across the whole bot.

### CODE REVIEW

**Comment by WardPearce** [comment]
Also instead of storing the aiohttp session in the ApiHelper class maybe using a singleton is a better idea.

**Comment by cameronshinn** [comment]
Hey @WardPearce before you make any changes, would you consider working off of the [`utils-refactor`](https://github.com/WardPearce/csgo-league-bot/tree/utils-refactor) branch? I am working on there right now to do some major refactoring so that building out features in the future will be easier. The `api.py` file is only moved to another location, but if you plan on making other changes it would probably help me when the time comes to merge.

I like the docstrings and arg/return types. I have been too lazy to clean all that up myself.

Also could you stick to using f-strings and single quotes to keep it consistent with the rest of the code?

**Comment by WardPearce** [comment]
f-strings and single quotes do hurt my soul but yea sure 😊
I'll look over https://github.com/WardPearce/csgo-league-bot/tree/utils-refactor whenever I get a chance.

**Comment by WardPearce** [comment]
https://www.encode.io/databases/
https://www.sqlalchemy.org/

Worth moving away from raw sql too

**Comment by cameronshinn** [comment]
That branch is very WIP right now but the `ApiHelper` is untouched, just moved to the `cogs/utils/` folder. I think it runs, but there may be bugs and I am working to get it fleshed out right now.

**Comment by cameronshinn** [comment]
> Also instead of storing the aiohttp session in the ApiHelper class maybe using a singleton is a better idea.

I was thinking of moving the session outside of the `ApiHelper` class and initialization outside of the event loop. Would just use the `ApiHelper` as a namespace mostly.

**Comment by WardPearce** [comment]
I'll make some adjustments so the aiohttp session is initialized inside the loop but isn't part of the  `ApiHelper` class

**Pull request closed without merging**
